version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    groups:
      production-dependencies-major:
        dependency-type: "production"
        update-types:
          - major
        patterns:
          - "*"
      production-dependencies-minor:
        dependency-type: "production"
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      development-dependencies-major:
        dependency-type: "development"
        update-types:
          - major
        patterns:
          - "*"
      development-dependencies-minor:
        dependency-type: "development"
        update-types:
          - minor
          - patch
        patterns:
          - "*"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@types/node"
        versions:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 10
