version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 10
