packages:
  - apps/*
  - packages/*
  - actions/*

catalog:
  "@actions/core": 1.11.1
  "@actions/exec": 1.1.1
  "@actions/github": 6.0.1
  "@eslint/js": 9.38.0
  "@google-analytics/data": 5.2.1
  "@heroicons/react": 2.2.0
  "@inquirer/prompts": 7.9.0
  "@next/bundle-analyzer": 16.0.0
  "@next/eslint-plugin-next": 16.0.0
  "@next/third-parties": 16.0.0
  "@sentry/nextjs": 10.21.0
  "@supercharge/promise-pool": 3.2.0
  "@tailwindcss/postcss": 4.1.15
  "@trivago/prettier-plugin-sort-imports": 5.2.2
  "@types/node": 22.18.6
  "@types/react": 19.2.2
  "@vercel/ncc": 0.38.4
  cheerio: 1.1.2
  domhandler: 5.0.3
  eslint: 9.38.0
  eslint-plugin-import: 2.32.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-turbo: 2.5.8
  knip: 5.66.2
  next: 16.0.0
  next-sitemap: 4.2.3
  next-themes: 0.4.6
  pdfjs-dist: 5.4.296
  postcss: 8.5.6
  prettier: 3.6.2
  prettier-plugin-tailwindcss: 0.7.1
  protobufjs: 7.5.4
  react: 19.2.0
  react-dom: 19.2.0
  react-share: 5.2.2
  recharts: 3.3.0
  strip-json-comments: 5.0.3
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.15
  turbo: 2.5.8
  typed.js: 2.1.0
  typescript: 5.9.3
  typescript-eslint: 8.46.2
  undici: 7.16.0

catalogMode: strict

onlyBuiltDependencies:
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - esbuild
  - oxc-resolver
  - protobufjs
  - sharp

updateConfig:
  ignoreDependencies:
    - "@types/node"
