packages:
  - apps/*
  - packages/*
  - actions/*
  - tooling/*

catalog:
  "@actions/core": 2.0.1
  "@actions/exec": 2.0.0
  "@actions/github": 6.0.1
  "@eslint/js": 9.39.2
  "@google-analytics/data": 5.2.1
  "@heroicons/react": 2.2.0
  "@inquirer/prompts": 8.1.0
  "@next/bundle-analyzer": 16.1.1
  "@next/third-parties": 16.1.1
  "@sentry/nextjs": 10.32.1
  "@supercharge/promise-pool": 3.2.0
  "@tailwindcss/postcss": 4.1.18
  "@trivago/prettier-plugin-sort-imports": 6.0.1
  "@types/node": 24.10.3
  "@types/react": 19.2.7
  "@vercel/ncc": 0.38.4
  babel-plugin-react-compiler: 1.0.0
  cheerio: 1.1.2
  domhandler: 5.0.3
  eslint: 9.39.2
  eslint-config-next: 16.1.1
  eslint-plugin-import: 2.32.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-turbo: 2.7.3
  knip: 5.80.0
  next: 16.1.1
  next-sitemap: 4.2.3
  next-themes: 0.4.6
  pdfjs-dist: 5.4.530
  postcss: 8.5.6
  prettier: 3.7.4
  prettier-plugin-tailwindcss: 0.7.2
  protobufjs: 8.0.0
  react: 19.2.3
  react-dom: 19.2.3
  react-share: 5.2.2
  recharts: 3.6.0
  strip-json-comments: 5.0.3
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  turbo: 2.7.3
  typed.js: 2.1.0
  typescript: 5.9.3
  typescript-eslint: 8.52.0
  undici: 7.18.0

catalogMode: strict

onlyBuiltDependencies:
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - esbuild
  - oxc-resolver
  - protobufjs
  - sharp
  - unrs-resolver

updateConfig:
  ignoreDependencies:
    - "@types/node"
