packages:
  - apps/*
  - packages/*
  - actions/*
  - tooling/*

catalog:
  "@actions/core": 3.0.0
  "@actions/exec": 3.0.0
  "@actions/github": 9.0.0
  "@eslint/js": 10.0.1
  "@google-analytics/data": 5.2.1
  "@heroicons/react": 2.2.0
  "@inquirer/prompts": 8.2.1
  "@next/bundle-analyzer": 16.1.6
  "@next/third-parties": 16.1.6
  "@rollup/plugin-commonjs": 29.0.0
  "@rollup/plugin-node-resolve": 16.0.3
  "@rollup/plugin-typescript": 12.3.0
  "@sentry/nextjs": 10.39.0
  "@supercharge/promise-pool": 3.2.0
  "@tailwindcss/postcss": 4.1.18
  "@trivago/prettier-plugin-sort-imports": 6.0.2
  "@types/node": 24.10.13
  "@types/react": 19.2.14
  babel-plugin-react-compiler: 1.0.0
  cheerio: 1.2.0
  domhandler: 5.0.3
  eslint: 10.0.0
  eslint-config-next: 16.1.6
  eslint-plugin-import: 2.32.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-turbo: 2.8.9
  knip: 5.83.1
  next: 16.1.6
  next-sitemap: 4.2.3
  next-themes: 0.4.6
  pdfjs-dist: 5.4.624
  postcss: 8.5.6
  prettier: 3.8.1
  prettier-plugin-tailwindcss: 0.7.2
  protobufjs: 8.0.0
  react: 19.2.4
  react-dom: 19.2.4
  react-share: 5.2.2
  recharts: 3.7.0
  rollup: 4.57.1
  strip-json-comments: 5.0.3
  tailwind-merge: 3.4.1
  tailwindcss: 4.1.18
  turbo: 2.8.9
  typed.js: 3.0.0
  typescript: 5.9.3
  typescript-eslint: 8.56.0
  undici: 7.22.0

catalogMode: strict

onlyBuiltDependencies:
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - esbuild
  - oxc-resolver
  - protobufjs
  - sharp
  - unrs-resolver

updateConfig:
  ignoreDependencies:
    - "@types/node"
