export const COMMIT_MESSAGE = "chore(party-data): Update standpoints";
export const PR_BODY =
  "This PR was automatically generated by the update-standpoints action.";

export const BRANCH_NAME = "action/update-standpoints";
export const PR_BASE = "main";
export const TEMP_BRANCH_NAME = `temp-${BRANCH_NAME}`;

export const GIT_USERNAME = "github-actions[bot]";
export const GIT_EMAIL = "github-actions[bot]@users.noreply.github.com";
